import type { PageConfig } from "@/app/components/types/ui";
import type { AdminRecord } from "@/app/sections/shared/config/shared";
import { CourseContentHierarchyPage } from "@/app/sections/products/pages/CourseContentHierarchyPage";
import {
  createAction,
  createPage,
  createRecord,
  createRowAction,
  createStat,
  metricColumn,
  nameColumn,
  searchFilter,
  selectFilter,
  standardStatusOptions,
  statusColumn,
  textColumn,
  updatedColumn,
} from "@/app/sections/shared/config/shared";

const productActions = [
  createRowAction("preview", "Preview", (row) => `Preview opened for ${row.name}.`),
  createRowAction("edit", "Edit Product", (row) => `Product editor opened for ${row.name}.`),
  createRowAction("publish", "Publish / Unpublish", (row) => `Publishing controls opened for ${row.name}.`),
  createRowAction("instructors", "Manage Instructors", (row) => `Instructor management opened for ${row.name}.`),
  createRowAction("sync", "Sync with LW", (row) => `Sync started for ${row.name}.`, "ghost"),
];

export const productPages: PageConfig<AdminRecord>[] = [
  createPage({
    id: "all-products",
    path: "products/all-products",
    title: "All Products",
    section: "Products",
    description: "Manage catalog structure, merchandising state, and publishing health.",
    stats: [
      createStat({ id: "prod-total", label: "Products", value: "184", change: "+9", tone: "success", icon: "products" }),
      createStat({ id: "prod-live", label: "Published", value: "138", change: "+4.1%", tone: "success", icon: "chart" }),
      createStat({ id: "prod-draft", label: "Drafts", value: "31", change: "Editorial", tone: "warning", icon: "document" }),
      createStat({ id: "prod-archived", label: "Archived", value: "15", change: "Stable", tone: "info", icon: "system" }),
    ],
    actions: [
      createAction("new-product", "New Product", "Product builder opened.", "primary", "products"),
      createAction("refresh-catalog", "Refresh Catalog", "Catalog refresh started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search products or owners"),
      selectFilter("status", "Status", [
        { label: "Published", value: "published" },
        { label: "Pending Approval", value: "pending approval" },
        { label: "Draft", value: "draft" },
      ], { columnId: "status" }),
      selectFilter("type", "Type", [
        { label: "Course", value: "course" },
        { label: "Event", value: "event" },
        { label: "Bundle", value: "bundle" },
        { label: "Community", value: "community" },
      ], { columnId: "category" }),
    ],
    enableSearchFieldSelector: true,
    searchFields: [
      { id: "name", label: "Product" },
      { id: "category", label: "Category" },
      { id: "owner", label: "Owner" },
      { id: "metric", label: "Enrollments" },
      { id: "status", label: "Status" },
    ],
    sortOptions: [
      { id: "updated-desc", label: "Updated (Newest)", columnId: "updatedAt", direction: "desc" },
      { id: "updated-asc", label: "Updated (Oldest)", columnId: "updatedAt", direction: "asc" },
      { id: "title-asc", label: "Title (A-Z)", columnId: "name", direction: "asc" },
      { id: "title-desc", label: "Title (Z-A)", columnId: "name", direction: "desc" },
      { id: "enrollments-high", label: "Enrollments (High to Low)", columnId: "metric", direction: "desc" },
      { id: "enrollments-low", label: "Enrollments (Low to High)", columnId: "metric", direction: "asc" },
    ],
    columns: [
      nameColumn("Product"),
      textColumn("category", "Category"),
      textColumn("owner", "Owner"),
      metricColumn("Enrollments"),
      statusColumn(),
      updatedColumn(),
    ],
    bulkActions: [
      { id: "publish", label: "Publish Selected", message: (rows) => `Publish would run for ${rows.length} selected products.` },
      { id: "unpublish", label: "Unpublish Selected", message: (rows) => `Unpublish would run for ${rows.length} selected products.` },
      { id: "add-category", label: "Add to Category", message: (rows) => `Category assignment would open for ${rows.length} selected products.` },
      { id: "feature", label: "Feature / Unfeature", message: (rows) => `Featuring would update ${rows.length} selected products.` },
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "courses",
    path: "products/courses",
    title: "Courses",
    section: "Products",
    description: "Track course lifecycle, instructional ownership, and conversion performance.",
    stats: [
      createStat({ id: "course-live", label: "Live courses", value: "94", change: "+6", tone: "success", icon: "products" }),
      createStat({ id: "course-review", label: "Needs QA", value: "12", change: "This week", tone: "warning", icon: "document" }),
      createStat({ id: "course-complete", label: "Avg. completion", value: "68%", change: "+3 pts", tone: "success", icon: "chart" }),
      createStat({ id: "course-nps", label: "Avg. rating", value: "4.7", change: "Strong", tone: "info", icon: "community" }),
    ],
    actions: [
      createAction("new-course", "New Course", "Course authoring flow opened.", "primary", "products"),
      createAction("export-course", "Export", "Course report exported.", "secondary", "document"),
    ],
    filters: [
      searchFilter("Search courses or instructors"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Course"),
      textColumn("owner", "Lead Instructor"),
      textColumn("plan", "Format"),
      metricColumn("Completion"),
      statusColumn(),
      updatedColumn(),
    ],
    rows: [
      createRecord({ id: "course-1", name: "Data Storytelling Essentials", subtitle: "Story-first analytics course", owner: "Ava Morgan", plan: "Self-paced", metric: "72%", status: "Active", updatedAt: "Today" }),
      createRecord({ id: "course-2", name: "Manager Enablement Sprint", subtitle: "Leadership operating rhythms", owner: "Noah Bennett", plan: "Cohort", metric: "84%", status: "Active", updatedAt: "Yesterday" }),
      createRecord({ id: "course-3", name: "Creative Systems for Teams", subtitle: "Design ops for scaling teams", owner: "Mia Patel", plan: "Self-paced", metric: "61%", status: "Pending review", updatedAt: "Yesterday" }),
      createRecord({ id: "course-4", name: "Revenue Planning Workshop", subtitle: "Quarterly planning templates", owner: "Sophia Chen", plan: "Live workshop", metric: "55%", status: "Draft", updatedAt: "2 days ago" }),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "event-products",
    path: "products/event-products",
    title: "Event Products",
    section: "Products",
    description: "Monitor event catalog readiness, hosts, and seat allocation.",
    stats: [
      createStat({ id: "events-upcoming", label: "Upcoming events", value: "28", change: "+4", tone: "success", icon: "calendar" }),
      createStat({ id: "events-sold", label: "Sold-out", value: "7", change: "High demand", tone: "info", icon: "chart" }),
      createStat({ id: "events-waitlist", label: "Waitlists", value: "13", change: "Watch closely", tone: "warning", icon: "users" }),
      createStat({ id: "events-draft", label: "Draft events", value: "5", change: "Programming", tone: "warning", icon: "document" }),
    ],
    actions: [
      createAction("schedule-event", "Schedule Event", "Event scheduler opened.", "primary", "calendar"),
      createAction("sync-speakers", "Sync Speakers", "Speaker sync started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search events or hosts"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Event"),
      textColumn("owner", "Host"),
      textColumn("location", "Venue"),
      metricColumn("Seats"),
      statusColumn(),
      updatedColumn("Starts"),
    ],
    rows: [
      createRecord({ id: "event-1", name: "Q2 Leadership Summit", subtitle: "Virtual executive event", owner: "Olivia Hart", location: "Online", metric: "412 / 500", status: "Active", updatedAt: "Apr 16" }),
      createRecord({ id: "event-2", name: "Design Critique Clinic", subtitle: "Interactive mentor session", owner: "Nina Alvarez", location: "San Francisco", metric: "60 / 60", status: "Sold out", updatedAt: "Apr 18" }),
      createRecord({ id: "event-3", name: "Retention Systems AMA", subtitle: "Subscriber operations panel", owner: "Ethan Rivera", location: "Online", metric: "122 / 150", status: "Active", updatedAt: "Apr 23" }),
      createRecord({ id: "event-4", name: "Growth Ops Roundtable", subtitle: "Closed enterprise cohort", owner: "Jordan Malik", location: "New York", metric: "Draft", status: "Draft", updatedAt: "May 2" }),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "session-instances",
    path: "products/session-instances",
    title: "Session Instances",
    section: "Products",
    description: "Review live delivery sessions, facilitators, and seat utilization.",
    stats: [
      createStat({ id: "session-week", label: "Sessions this week", value: "46", change: "+5", tone: "success", icon: "calendar" }),
      createStat({ id: "session-fill", label: "Avg. fill rate", value: "81%", change: "+2 pts", tone: "success", icon: "chart" }),
      createStat({ id: "session-risk", label: "At risk", value: "6", change: "Low attendance", tone: "warning", icon: "system" }),
      createStat({ id: "session-hosts", label: "Facilitators", value: "24", change: "Assigned", tone: "info", icon: "users" }),
    ],
    actions: [
      createAction("new-session", "Create Session", "Session creation dialog opened.", "primary", "calendar"),
      createAction("bulk-reschedule", "Reschedule", "Bulk reschedule started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search sessions or facilitators"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Session"),
      textColumn("owner", "Facilitator"),
      textColumn("location", "Delivery"),
      metricColumn("Utilization"),
      statusColumn(),
      updatedColumn("Date"),
    ],
    rows: [
      createRecord({ id: "session-1", name: "Leadership Accelerator - Group A", subtitle: "Week 3 live discussion", owner: "Nina Alvarez", location: "Zoom", metric: "92%", status: "Active", updatedAt: "Apr 9" }),
      createRecord({ id: "session-2", name: "Leadership Accelerator - Group B", subtitle: "Week 3 live discussion", owner: "Nina Alvarez", location: "Zoom", metric: "88%", status: "Active", updatedAt: "Apr 10" }),
      createRecord({ id: "session-3", name: "Revenue Planning Workshop", subtitle: "CFO office hours", owner: "Sophia Chen", location: "Online", metric: "61%", status: "Pending review", updatedAt: "Apr 11" }),
      createRecord({ id: "session-4", name: "Ops Playbook Live", subtitle: "Cohort kickoff", owner: "Jordan Malik", location: "New York", metric: "46%", status: "Draft", updatedAt: "Apr 22" }),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "bundles",
    path: "products/bundles",
    title: "Bundles",
    section: "Products",
    description: "Manage packaged offers, attach pricing logic, and monitor attach rate.",
    stats: [
      createStat({ id: "bundle-live", label: "Live bundles", value: "16", change: "+2", tone: "success", icon: "products" }),
      createStat({ id: "bundle-attach", label: "Attach rate", value: "21%", change: "+3 pts", tone: "success", icon: "chart" }),
      createStat({ id: "bundle-trial", label: "Trial bundles", value: "5", change: "Testing", tone: "info", icon: "document" }),
      createStat({ id: "bundle-retire", label: "Retire soon", value: "2", change: "Watch", tone: "warning", icon: "system" }),
    ],
    actions: [
      createAction("new-bundle", "Create Bundle", "Bundle builder opened.", "primary", "products"),
      createAction("pricing-audit", "Pricing Audit", "Pricing audit started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search bundles or owners"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Bundle"),
      textColumn("owner", "Owner"),
      textColumn("plan", "Offer Type"),
      metricColumn("Attach Rate"),
      statusColumn(),
      updatedColumn(),
    ],
    rows: [
      createRecord({ id: "bundle-1", name: "Leadership + Coaching Bundle", subtitle: "Course plus private sessions", owner: "Olivia Hart", plan: "Upsell", metric: "24%", status: "Active", updatedAt: "Today" }),
      createRecord({ id: "bundle-2", name: "Marketing Sprint Pack", subtitle: "Workshop and templates", owner: "Ethan Rivera", plan: "Launch", metric: "19%", status: "Active", updatedAt: "Yesterday" }),
      createRecord({ id: "bundle-3", name: "Team Success Bundle", subtitle: "Enterprise onboarding collection", owner: "Ava Morgan", plan: "Enterprise", metric: "31%", status: "Pending review", updatedAt: "Yesterday" }),
      createRecord({ id: "bundle-4", name: "Legacy Growth Pack", subtitle: "Retiring offer", owner: "Jordan Malik", plan: "Promo", metric: "9%", status: "Draft", updatedAt: "Last week" }),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "course-content",
    path: "products/course-content",
    title: "Course Content",
    section: "Products",
    description: "Audit lessons, asset ownership, and publication readiness at the content level.",
    component: CourseContentHierarchyPage,
  }),
];
