import type { PageConfig } from "@/app/components/types/ui";
import type { AdminRecord } from "@/app/sections/shared/config/shared";
import { CourseContentHierarchyPage } from "@/app/sections/products/pages/CourseContentHierarchyPage";
import {
  createAction,
  createPage,
  createRowAction,
  metricColumn,
  nameColumn,
  searchFilter,
  selectFilter,
  standardStatusOptions,
  statusColumn,
  textColumn,
  updatedColumn,
} from "@/app/sections/shared/config/shared";

const productActions = [
  createRowAction("preview", "Preview", (row) => `Preview opened for ${row.name}.`),
  createRowAction("edit", "Edit Product", (row) => `Product editor opened for ${row.name}.`),
  createRowAction("publish", "Publish / Unpublish", (row) => `Publishing controls opened for ${row.name}.`),
  createRowAction("instructors", "Manage Instructors", (row) => `Instructor management opened for ${row.name}.`),
  createRowAction("sync", "Sync with LW", (row) => `Sync started for ${row.name}.`, "ghost"),
];

export const productPages: PageConfig<AdminRecord>[] = [
  createPage({
    id: "all-products",
    path: "products/all-products",
    title: "All Products",
    section: "Products",
    dataMode: "server",
    useLegacyData: false,
    density: "comfortable",
    defaultPageSize: 25,
    rowsPerPageOptions: [10, 25, 50, 100],
    defaultSortColumn: "updatedAt",
    description: "Manage catalog structure, merchandising state, and publishing health.",
    actions: [
      createAction("new-product", "New Product", "Product builder opened.", "primary", "products"),
      createAction("refresh-catalog", "Refresh Catalog", "Catalog refresh started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search products or owners"),
      selectFilter("status", "Status", [
        { label: "Published", value: "published" },
        { label: "Pending Approval", value: "pending approval" },
        { label: "Draft", value: "draft" },
      ], { columnId: "status" }),
      selectFilter("type", "Type", [
        { label: "Course", value: "course" },
        { label: "Event", value: "event" },
        { label: "Bundle", value: "bundle" },
        { label: "Community", value: "community" },
      ], { columnId: "category" }),
    ],
    enableSearchFieldSelector: true,
    searchFields: [
      { id: "name", label: "Product" },
      { id: "category", label: "Category" },
      { id: "owner", label: "Owner" },
      { id: "metric", label: "Enrollments" },
      { id: "status", label: "Status" },
    ],
    sortOptions: [
      { id: "updated-desc", label: "Updated (Newest)", columnId: "updatedAt", direction: "desc" },
      { id: "updated-asc", label: "Updated (Oldest)", columnId: "updatedAt", direction: "asc" },
      { id: "title-asc", label: "Title (A-Z)", columnId: "name", direction: "asc" },
      { id: "title-desc", label: "Title (Z-A)", columnId: "name", direction: "desc" },
      { id: "enrollments-high", label: "Enrollments (High to Low)", columnId: "metric", direction: "desc" },
      { id: "enrollments-low", label: "Enrollments (Low to High)", columnId: "metric", direction: "asc" },
    ],
    columns: [
      nameColumn("Product"),
      textColumn("category", "Category"),
      textColumn("owner", "Owner"),
      metricColumn("Enrollments"),
      statusColumn(),
      updatedColumn(),
    ],
    bulkActions: [
      { id: "publish", label: "Publish Selected", message: (rows) => `Publish would run for ${rows.length} selected products.` },
      { id: "unpublish", label: "Unpublish Selected", message: (rows) => `Unpublish would run for ${rows.length} selected products.` },
      { id: "add-category", label: "Add to Category", message: (rows) => `Category assignment would open for ${rows.length} selected products.` },
      { id: "feature", label: "Feature / Unfeature", message: (rows) => `Featuring would update ${rows.length} selected products.` },
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "courses",
    path: "products/courses",
    title: "Courses",
    section: "Products",
    dataMode: "server",
    useLegacyData: false,
    density: "comfortable",
    defaultPageSize: 25,
    rowsPerPageOptions: [10, 25, 50, 100],
    defaultSortColumn: "updatedAt",
    description: "Track course lifecycle, instructional ownership, and conversion performance.",
    actions: [
      createAction("new-course", "New Course", "Course authoring flow opened.", "primary", "products"),
      createAction("export-course", "Export", "Course report exported.", "secondary", "document"),
    ],
    filters: [
      searchFilter("Search courses or instructors"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Course"),
      textColumn("owner", "Lead Instructor"),
      textColumn("plan", "Format"),
      metricColumn("Completion"),
      statusColumn(),
      updatedColumn(),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "event-products",
    path: "products/event-products",
    title: "Event Products",
    section: "Products",
    dataMode: "server",
    useLegacyData: false,
    density: "comfortable",
    defaultPageSize: 25,
    rowsPerPageOptions: [10, 25, 50, 100],
    defaultSortColumn: "updatedAt",
    description: "Monitor event catalog readiness, hosts, and seat allocation.",
    actions: [
      createAction("schedule-event", "Schedule Event", "Event scheduler opened.", "primary", "calendar"),
      createAction("sync-speakers", "Sync Speakers", "Speaker sync started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search events or hosts"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Event"),
      textColumn("owner", "Host"),
      textColumn("location", "Venue"),
      metricColumn("Seats"),
      statusColumn(),
      updatedColumn("Starts"),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "session-instances",
    path: "products/session-instances",
    title: "Session Instances",
    section: "Products",
    dataMode: "server",
    useLegacyData: false,
    density: "comfortable",
    defaultPageSize: 25,
    rowsPerPageOptions: [10, 25, 50, 100],
    defaultSortColumn: "updatedAt",
    description: "Review live delivery sessions, facilitators, and seat utilization.",
    actions: [
      createAction("new-session", "Create Session", "Session creation dialog opened.", "primary", "calendar"),
      createAction("bulk-reschedule", "Reschedule", "Bulk reschedule started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search sessions or facilitators"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Session"),
      textColumn("owner", "Facilitator"),
      textColumn("location", "Delivery"),
      metricColumn("Utilization"),
      statusColumn(),
      updatedColumn("Date"),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "bundles",
    path: "products/bundles",
    title: "Bundles",
    section: "Products",
    dataMode: "server",
    useLegacyData: false,
    density: "comfortable",
    defaultPageSize: 25,
    rowsPerPageOptions: [10, 25, 50, 100],
    defaultSortColumn: "updatedAt",
    description: "Manage packaged offers, attach pricing logic, and monitor attach rate.",
    actions: [
      createAction("new-bundle", "Create Bundle", "Bundle builder opened.", "primary", "products"),
      createAction("pricing-audit", "Pricing Audit", "Pricing audit started.", "secondary", "refresh"),
    ],
    filters: [
      searchFilter("Search bundles or owners"),
      selectFilter("status", "Status", standardStatusOptions()),
    ],
    columns: [
      nameColumn("Bundle"),
      textColumn("owner", "Owner"),
      textColumn("plan", "Offer Type"),
      metricColumn("Attach Rate"),
      statusColumn(),
      updatedColumn(),
    ],
    rowActions: productActions,
  }),
  createPage({
    id: "course-content",
    path: "products/course-content",
    title: "Course Content",
    section: "Products",
    description: "Audit lessons, asset ownership, and publication readiness at the content level.",
    component: CourseContentHierarchyPage,
  }),
];
